fix: Error handling & coding style
yeha98555/ticket-haven-server pull request #17
Opened 2023-05-15 16:56 UTC by pageshih

2023-05-16 01:28 UTC, yurychang commented on src/controllers/user.ts
>        const result = await userService.signin(req.body);
userService.signin 我會改成只回傳 token，message 則寫在 controller 裡

2023-05-16 01:28 UTC, yurychang commented on src/controllers/user.ts
console.log 可以移除

2023-05-16 01:28 UTC, yurychang commented on src/services/user.ts
> +    try {
不需要這個try catch, 全域的error handler 會自動記錄

2023-05-16 01:28 UTC, yurychang commented on src/services/user.ts
> +    } catch (err) {
這種未知的 Error 可以讓全域ErrorHandler處理，不然應該手動呼叫logError來記錄

2023-05-16 01:29 UTC, yurychang commented on src/models/user.ts
> +      minlength: 8,
字數限制不能加在這，password 是 hash 過的值，要在一開始就驗證

2023-05-16 01:29 UTC, yurychang requested changes
> 字數限制不能加在這，password 是 hash 過的值，要在一開始就驗證

2023-05-16 01:30 UTC, yurychang requested changes
> successBody 我有改過，現在要寫成
```typescript
res.json(Body.success(token).message(message))
```

2023-05-16 06:51 UTC, pageshih commented on src/controllers/user.ts
>        const result = await userService.signin(req.body);
好奇想問會這樣拆的原因是什麼?

2023-05-16 06:59 UTC, pageshih commented on src/controllers/user.ts
>      try {
想問這邊為什麼會想把 try catch 本身再拉出來做成一個 function ?
如果都用這個 function 來做 try catch 這樣會不會變成耦合性過高?

2023-05-16 07:54 UTC, yurychang commented on src/controllers/user.ts
>      try {
跟express 的錯誤處理方式有關，express會catch從middleware中拋出的error，然後交給專門處理錯誤的middleware處理。
而非預期錯誤就是一種可以交由全域錯誤處理的error，所以才不需要加上try/catch，讓error拋到外部。
至於catchAsyncError，並不是為了加上try/catch，而是因為express不會自動catch async拋出的 error，所以我們手動幫express catch 住，再用next傳下去。

2023-05-16 09:46 UTC, yurychang commented on src/controllers/user.ts
>        const result = await userService.signin(req.body);
我認為service 的職責是實現後段系統內的功能，不需要考慮回傳給api 使用者的訊息，所以message應該由controller來定義。

2023-05-16 12:26 UTC, pageshih commented on src/controllers/user.ts
>      try {
所以這個意思是說，
傳進去的 async function 要自定義 error obj 的話，還是需要包 try catch 把原生 error 接住，
然後再 throw 自定義的 error 給 catchAsyncError 接嗎？

2023-05-16 12:32 UTC, yurychang commented on src/controllers/user.ts
>      try {
對啊，appError就是

2023-05-16 12:34 UTC, yurychang commented on src/controllers/user.ts
>      try {
但如果沒有要交給全域處理，就不用再throw出去

2023-05-16 12:35 UTC, yurychang commented on src/controllers/user.ts
>        const result = await userService.signin(req.body);
是，但這部分的寫法現在還沒很完善，要再調整一下

2023-05-16 15:09 UTC, yurychang commented on src/controllers/user.ts
>        const result = await userService.signin(req.body);
可以參考 https://stackoverflow.com/questions/70681202/is-it-good-way-to-throw-error-from-service-in-nestjs-like-it，_But I suggest to decide on controller level_ ...

2023-05-17 16:14 UTC, yurychang approved these changes
可以先 merge 了，有空再調整。
自訂錯誤的寫法可以先參考 https://github.com/yeha98555/ticket-haven-server/pull/19，目前還沒定下來，可以再討論。

2023-05-17 16:14 UTC, yurychang commented on src/controllers/user.ts
> +      if(!token) throw appError(400, StatusCode.FAIL, 'Invalid request');
同樣可以自訂錯誤

2023-05-17 16:16 UTC, merged