Feature/get event info api
yeha98555/ticket-haven-server pull request #32
Opened 2023-05-27 04:37 UTC by yeha98555

完成
- 取得票價區、座位銷售狀況API
- 在activites schema加入color資訊

假資料主要用在activities._id = "61697b11c0cb54d45f7c8dcb"的事件上，參考 https://i-chen.kktix.cc/events/806cc753-02be1 座位圖。

2023-05-27 08:51 UTC, yurychang requested changes

2023-05-27 08:51 UTC, yurychang commented on src/services/event.ts
> +    ]);
應該要改成從 seat_reservation 去撈。
目前購票流程如下：產生訂單->同時在 seat_reservation 預約座位 ? 付款完成->產生票卷 : 逾期-> 移除訂單和seat_reservation

2023-05-27 08:53 UTC, yurychang commented on src/services/event.ts
> +    }).select([
events._id 其實用 string 也可以

2023-05-27 23:40 UTC, yeha98555 commented on src/services/event.ts
> +    ]);
喔喔好，我忘記 `seat_reservation` 它了。想確認所以 `seat_reservation` 裡面有已經賣出和被正在結帳中的票嗎？只有在超過結帳時間未結帳、活動場次結束，才會從 `seat_reservation` 中移除？

2023-05-27 23:41 UTC, yeha98555 commented on src/services/event.ts
> +    }).select([
阿阿，我下面改了，上面忘記改到，感謝提醒。

2023-05-27 23:57 UTC, yeha98555 commented on src/services/event.ts
> +    ]);
我剛剛看了 `seat_reservation` 資料結構，為什麼 `area_id`、`subarea_id` 儲存在外層？而是放在每個 `seat` 底下？因為我想說每張訂單裡的座位 `area_id`、`subarea_id` 應該會都一樣，依照原本設計的購票流程。如果這樣放，我在取資料時就需要多一個迴圈判斷。

2023-05-28 02:47 UTC, yurychang commented on src/services/event.ts
> +    ]);
> 喔喔好，抱歉我忘記 `seat_reservation` 它了。想確認所以 `seat_reservation` 裡面有已經賣出和被正在結帳中的票嗎？只有在超過結帳時間未結帳、活動場次結束，才會從 `seat_reservation` 中移除？

對，活動結束要不要移除應該都可以

2023-05-28 02:48 UTC, yurychang commented on src/services/event.ts
> +    ]);
> 我剛剛看了 `seat_reservation` 資料結構，為什麼 `area_id`、`subarea_id` 是放在每個 `seat` 底下？不是放在 `seat` 的外層？因為我想說每張訂單裡的座位 `area_id`、`subarea_id` 應該會都一樣，依照原本設計的購票流程。如果這樣放，我在取資料時就需要多一個迴圈判斷。

購票流程繼續選購時是可以選不同區域的

2023-05-28 12:13 UTC, yeha98555 commented on src/services/event.ts
> +    ]);
喔喔了解，已經修改好了。

2023-05-28 12:52 UTC, yurychang approved these changes

2023-05-28 12:54 UTC, merged