Feature/signup,signin
yeha98555/ticket-haven-server pull request #8
Opened 2023-05-08 15:45 UTC by pageshih

2023-05-09 09:34 UTC, yurychang commented
第三方註冊時會強制使用者建立帳密嗎? 會影響 user model 的必填欄位

2023-05-14 04:43 UTC, pageshih commented
有更新 ＪＷＴ 跟 加密的部分上去
然後上面的 appError 我想說接下來重構的時候調整，
目前先按照這個樣子，再麻煩看一下～

2023-05-14 04:47 UTC, pageshih commented on src/services/user.ts
> +  signin: async ({email, password}: {email: string, password: string}) => {
那 service 要放什麼？

2023-05-14 06:12 UTC, yurychang requested changes

2023-05-14 06:12 UTC, yurychang commented on src/services/user.ts
> +    const isExistUser = await UserModel.findOneAndDelete({email})
不能用 findOneAndDelete，改成 findOne

2023-05-14 07:09 UTC, yeha98555 commented on src/services/user.ts
> +  signin: async ({email, password}: {email: string, password: string}) => {
原本覺得要複雜的業務邏輯才會拆到service，但後來發現有些也會像你這樣拆。

2023-05-14 07:37 UTC, yeha98555 reviewed
review完成，建議：
- JWT的`expiresIn`覺得之後可以存環境變數。
- 縮排好像跟不太一樣。

針對程式碼的則如下conversations。

2023-05-14 07:37 UTC, yeha98555 commented on src/services/user.ts
> +              UserModel.find({}).then((data)=> console.log(data));
這句話好像可以刪除。

2023-05-14 07:37 UTC, yeha98555 commented on src/services/user.ts
> +    const isExistUser = await UserModel.findOneAndDelete({email})
應該是`findOne({email})`，如果有delete，這樣可以重複註冊，蓋掉之前的user資料。

2023-05-14 08:08 UTC, yurychang reviewed
之後可以加入email、password格式驗證

2023-05-14 12:05 UTC, pageshih commented on src/services/user.ts
> +    const isExistUser = await UserModel.findOneAndDelete({email})
阿，這邊是因為我想要刪掉我測試用的帳號，忘記改回來了
我再改改

2023-05-14 12:06 UTC, pageshih commented on src/services/user.ts
> +        const msg = new Promise<Message>((resolve) => {
但是因為不包 Promise 我在 操作 DB 之後的訊息丟不出來

2023-05-14 12:10 UTC, pageshih commented on src/services/user.ts
> +            const SECRET: string = process.env.JWT_SECRET!;
但不加 Typescript 會報錯

2023-05-14 12:13 UTC, pageshih commented on src/services/user.ts
> +        bcrypt.hash(password, saltRounds, async (err, hash)=>{
我加 await typescript 提示說不可以作用在這個 function 上
實際測過加了await 我在裡面的訊息也沒辦法丟出來

2023-05-14 12:18 UTC, yurychang commented on src/services/user.ts
> +            const SECRET: string = process.env.JWT_SECRET!;
在我的環境不會耶，JWT_SECRET 有標注在enviroment.d.ts 裡，理論上也不會報錯。妳看到的錯誤是什麼呢？

2023-05-14 13:00 UTC, yurychang commented on src/services/user.ts
> +        const error = appError(404, StatusCode.NOT_FOUND, '帳號不存在！')
如果是這樣像也可

2023-05-14 14:30 UTC, yeha98555 commented on src/services/user.ts
> +        const error = appError(404, StatusCode.NOT_FOUND, '帳號不存在！')
但我自己過往的經驗都是回"帳號/密碼錯誤"，我揣測可能不要讓其他人輕易知道有哪些帳號已有。

2023-05-14 15:11 UTC, pageshih commented on src/services/user.ts
> +              UserModel.find({}).then((data)=> console.log(data));
已修改

2023-05-14 15:11 UTC, pageshih commented on src/services/user.ts
> +    const isExistUser = await UserModel.findOneAndDelete({email})
已修改

2023-05-14 15:21 UTC, yeha98555 approved these changes

2023-05-14 15:45 UTC, merged